# Generated by Django 5.2 on 2025-06-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchaise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
