# Generated by Django 5.2 on 2025-06-03 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_created_at_user_updated_at'),
        ('franchaise', '0002_franchise_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='city',
            field=models.CharField(default='Shillong', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='franchise',
            name='is_shortlisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='franchise',
            name='shortlisted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='shortlisted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shortlisted_franchises', to='account.admin'),
        ),
    ]
