# Generated by Django 5.2 on 2025-06-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchaise', '0003_franchise_city_franchise_is_shortlisted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SHORTLISTED', 'Shortlisted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
