# Generated by Django 5.2 on 2025-06-24 11:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchaise', '0004_franchise_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='franchise',
            name='franchaise_uuid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
