# Generated by Django 5.2 on 2025-07-15 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchaise', '0005_franchise_created_at_franchise_franchaise_uuid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_title', models.CharField(max_length=100)),
                ('progress_status', models.CharField(max_length=100)),
                ('comments', models.TextField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('NOT INTERESTED', 'not interested'), ('INTERESTED', 'interested'), ('PENDING', 'pending'), ('COMPLETED', 'completed'), ('FOLLOW UP', 'follow up')], default='PENDING', max_length=20)),
                ('source', models.CharField(max_length=100)),
                ('interested_service', models.CharField(max_length=100)),
                ('follow_up_dates', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(max_length=150)),
                ('notes', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='franchise_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
