# Generated by Django 5.2 on 2025-07-11 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreAssesment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathers_name', models.CharField(max_length=100)),
                ('mothers_name', models.CharField(max_length=100)),
                ('siblings_no', models.IntegerField(max_length=10)),
                ('family_occupation', models.CharField(max_length=100)),
                ('highest_qualification', models.TextField(help_text='Comma Seperated values')),
                ('relevant_subject', models.TextField(blank=True, help_text='Comma Seperated values', null=True)),
                ('performance_levels', models.TextField(blank=True, help_text='Comma Seperated values', null=True)),
                ('scolarships', models.TextField(blank=True, help_text='Comma Seperated values', null=True)),
                ('award_recognition', models.TextField(blank=True, help_text='Comma Seperated values', null=True)),
                ('strengths', models.TextField(blank=True, help_text='Comma Seperated values', null=True)),
                ('weaknesses', models.TextField(blank=True, help_text='Comma Seperated values', null=True)),
                ('hobbies', models.TextField(blank=True, help_text='Comma Seperated values', null=True)),
                ('sports', models.TextField(blank=True, help_text='Comma Seperated values', null=True)),
                ('voluntary_experiences', models.TextField(blank=True, help_text='Comma Seperated values', null=True)),
                ('other_relevant_experiences', models.TextField(blank=True, help_text='Comma Seperated values', null=True)),
                ('career_related_interests', models.TextField(help_text='Comma Seperated values')),
                ('career_values', models.TextField(help_text='Comma Seperated values')),
                ('technical_skills', models.TextField(blank=True, help_text='Comma Seperated values', null=True)),
                ('soft_skills', models.TextField(blank=True, help_text='Comma Seperated values', null=True)),
                ('other_relevant_skills', models.TextField(blank=True, help_text='Comma Seperated values', null=True)),
                ('part_time_internships', models.TextField(blank=True, help_text='Comma Seperated values', null=True)),
                ('career_related_projects', models.TextField(blank=True, help_text='Comma Seperated values', null=True)),
                ('career_revelant_work_experiences', models.TextField(blank=True, help_text='Comma Seperated values', null=True)),
                ('career_options', models.TextField(help_text='Comma Seperated values')),
                ('career_decision', models.TextField(help_text='Comma Seperated values')),
                ('parental_influence', models.CharField(max_length=100)),
                ('short_term_career_goals', models.TextField(help_text='Comma Seperated values')),
                ('long_term_career_goals', models.TextField(help_text='Comma Seperated values')),
                ('career_aspirations', models.TextField(help_text='Comma Seperated values')),
                ('social_environment', models.TextField(help_text='Comma Seperated values')),
                ('impact_of_social_environment', models.TextField(max_length=200)),
                ('your_expectation', models.TextField(max_length=200)),
                ('benifit_in_career_journey', models.TextField(max_length=200)),
                ('questions_about_counselling_process', models.TextField(max_length=200)),
                ('intend_to_pursue_abroad', models.TextField(max_length=200)),
                ('previously_explored_any_career_options', models.TextField(max_length=200)),
                ('preferred_learning_style', models.TextField(max_length=200)),
                ('any_believe_in_sc_and_ob_approach', models.TextField(max_length=200)),
                ('additional_info', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preassesment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
