# Generated by Django 5.2 on 2025-07-11 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preassesment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='preassesment',
            name='siblings_no',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='preassesment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preassesment', to=settings.AUTH_USER_MODEL),
        ),
    ]
