# Generated by Django 5.2 on 2025-07-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preassesment', '0002_alter_preassesment_siblings_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preassesment',
            name='siblings_no',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
