# Generated by Django 5.2 on 2025-08-06 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preassesment', '0002_alter_preassesment_siblings_no_and_more'),
        ('preassesment', '0003_alter_preassesment_siblings_no'),
    ]

    operations = [
    ]
