# Generated by Django 5.2 on 2025-06-09 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0002_counselingsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselorFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_date', models.DateField(auto_now_add=True)),
                ('feedback_text', models.TextField()),
                ('feedback_report', models.FileField(blank=True, null=True, upload_to='feedback_reports/')),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='counselor.counselor')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='counselor.counselingsession')),
            ],
        ),
    ]
