# Generated by Django 5.2 on 2025-07-07 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0003_counselorfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselor',
            name='current_occupation',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counselor',
            name='experience_in_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Counselor_background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counselling_specialization', models.TextField()),
                ('certification_qualification', models.TextField()),
                ('relevant_exp', models.IntegerField()),
                ('motivation_reason', models.TextField()),
                ('hope_reason', models.TextField()),
                ('is_terms_agreed', models.BooleanField(default=False)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselor', to='counselor.counselor')),
            ],
        ),
    ]
