# Generated by Django 5.2 on 2025-07-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0004_counselor_current_occupation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselor',
            name='current_occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
