# Generated by Django 5.2 on 2025-07-07 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0005_alter_counselor_current_occupation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counselor_background',
            name='is_terms_agreed',
        ),
        migrations.AddField(
            model_name='counselor',
            name='is_terms_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='counselor_background',
            name='counselor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backgrounds', to='counselor.counselor'),
        ),
    ]
