# Generated by Django 5.2 on 2025-07-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0006_remove_counselor_background_is_terms_agreed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counselor_background',
            name='hope_reason',
        ),
        migrations.RemoveField(
            model_name='counselor_background',
            name='motivation_reason',
        ),
        migrations.AddField(
            model_name='counselor',
            name='hope_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counselor',
            name='motivation_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
