# Generated by Django 5.2 on 2025-07-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0007_remove_counselor_background_hope_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselor',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
