# Generated by Django 5.2 on 2025-07-07 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0008_counselor_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselor_background',
            name='counselor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background', to='counselor.counselor'),
        ),
    ]
