# Generated by Django 5.2 on 2025-07-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0009_alter_counselor_background_counselor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselor_background',
            name='certification_qualification',
            field=models.ImageField(upload_to='certifications/'),
        ),
    ]
