# Generated by Django 5.2 on 2025-06-03 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counselor',
        ),
    ]
