# Generated by Django 5.2 on 2025-06-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_delete_counselor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
