# Generated by Django 5.2 on 2025-06-25 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('service', '0002_remove_service_price_service_base_price_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service', unique=True),
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
    ]
