# Generated by Django 5.2 on 2025-05-28 05:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='last_name',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='category',
            field=models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty'), ('Counselor', 'Counselor'), ('Executive', 'Executive'), ('Franchise', 'Franchise'), ('Others', 'Others')], default='Others', max_length=20),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiry',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
