# Generated by Django 5.2 on 2025-05-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_first_name_enquiry_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='category',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='form_submitted_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
