# Generated by Django 5.2 on 2025-06-03 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_types', to='career_test.category')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('user_group', models.CharField(choices=[('class_8_10', 'Class 8–10'), ('class_11_12', 'Class 11–12'), ('college', 'College Students'), ('working', 'Working Professionals')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('option_a_text', models.CharField(blank=True, max_length=255, null=True)),
                ('option_a_image', models.ImageField(blank=True, null=True, upload_to='option_images/')),
                ('option_b_text', models.CharField(blank=True, max_length=255, null=True)),
                ('option_b_image', models.ImageField(blank=True, null=True, upload_to='option_images/')),
                ('option_c_text', models.CharField(blank=True, max_length=255, null=True)),
                ('option_c_image', models.ImageField(blank=True, null=True, upload_to='option_images/')),
                ('option_d_text', models.CharField(blank=True, max_length=255, null=True)),
                ('option_d_image', models.ImageField(blank=True, null=True, upload_to='option_images/')),
                ('option_e_text', models.CharField(blank=True, max_length=255, null=True)),
                ('option_e_image', models.ImageField(blank=True, null=True, upload_to='option_images/')),
                ('option_f_text', models.CharField(blank=True, max_length=255, null=True)),
                ('option_f_image', models.ImageField(blank=True, null=True, upload_to='option_images/')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='career_test.testtype')),
            ],
        ),
    ]
