# Generated by Django 5.2 on 2025-06-25 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('franchaise', '0005_franchise_created_at_franchise_franchaise_uuid_and_more'),
        ('service', '0002_remove_service_price_service_base_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('franchaise_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='franchaise.franchise', to_field='franchaise_uuid')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
        ),
    ]
