# Generated by Django 5.2 on 2025-06-25 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
        ('franchaise', '0005_franchise_created_at_franchise_franchaise_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='franchaise_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='franchaise.franchise', to_field='franchaise_uuid'),
        ),
    ]
