# Generated by Django 5.2 on 2025-06-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_checkout_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
