# Generated by Django 5.2 on 2025-06-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_checkout_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='state',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkout',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
