# Generated by Django 5.2 on 2025-06-26 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_checkout_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='user',
        ),
    ]
