# Generated by Django 5.2 on 2025-08-06 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_checkout_status'),
        ('checkout', '0008_checkout_created_at_checkout_updated_at'),
    ]

    operations = [
    ]
