# Generated by Django 5.2 on 2025-07-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=13)),
                ('city', models.CharField(max_length=13)),
                ('preferred_destination', models.CharField()),
                ('is_coaching', models.BooleanField(default=False)),
                ('is_loan', models.BooleanField(default=False)),
            ],
        ),
    ]
