# Generated by Django 5.2 on 2025-07-10 11:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementEnquiry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementenquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placementenquiry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
