# Generated by Django 5.2 on 2025-07-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementEnquiry', '0002_placementenquiry_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementenquiry',
            name='nearest_office',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
