# Generated by Django 5.2 on 2025-07-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementEnquiry', '0003_placementenquiry_nearest_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementenquiry',
            name='nearest_office',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
