# Generated by Django 5.2 on 2025-06-05 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchaise', '0004_franchise_status'),
        ('student', '0002_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='franchaise.franchise'),
        ),
    ]
