# Generated by Django 5.2 on 2025-06-26 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_remove_service_price_service_base_price_and_more'),
        ('student', '0003_student_franchise'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='checkout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_checkout', to='service.service'),
        ),
        migrations.AddField(
            model_name='student',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_service', to='service.service'),
        ),
    ]
