# Generated by Django 5.2 on 2025-06-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_remove_service_price_service_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='is_avaiable',
            field=models.BooleanField(default=True),
        ),
    ]
