# Generated by Django 5.2 on 2025-06-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_servicetype_is_avaiable'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
